### ISSUE TITLE
准确率不符合

### ISSUE THREAD

**Issue by JohnVonneumann0828** [ppx-hub/PyTorch_VGG16_Cifar10#1]
您好，我用您的模型结构并且用一样的训练代码训练之后准确率只有77%，虽然可以用您的权重文件达到91但是我没有办法通过您的训练代码达到91%的准确率。

**Comment by ppx-hub** [comment]
您好，这份儿代码应该是没有任何删减了，不过没有固定随机种子。我今天下午也重新跑一下代码，我固定好种子后，重新上传到github上，肯定是可以复现的。

**Comment by ppx-hub** [comment]
> 您好，我用您的模型结构并且用一样的训练代码训练之后准确率只有77%，虽然可以用您的权重文件达到91但是我没有办法通过您的训练代码达到91%的准确率。

您好，这份儿代码应该是没有任何删减了，不过没有固定随机种子。我今天下午也重新跑一下代码，我固定好种子后，重新上传到github上，肯定是可以复现的。

**Comment by JohnVonneumann0828** [comment]
您好，我用您的代码用跑了一遍。代码没有问题，我复现的时候把损失函数搞错了。非常感谢您的代码！

**Comment by ppx-hub** [comment]
> 您好，我用您的代码用跑了一遍。代码没有问题，我复现的时候把损失函数搞错了。非常感谢您的代码！

不客气，上传了训练日志，可以参考。
